//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcECommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Orders = new HashSet<Orders>();
            this.Reviews = new HashSet<Reviews>();
            this.WishListToProducts = new HashSet<WishListToProducts>();
            this.WishListToProducts1 = new HashSet<WishListToProducts>();
        }
    
        public int ProductId { get; set; }
        public Nullable<byte> CategoryId { get; set; }
        public Nullable<byte> BrandId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public string ImageURL { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual ProductDetails ProductDetails { get; set; }
        public virtual Stores Stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reviews> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishListToProducts> WishListToProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishListToProducts> WishListToProducts1 { get; set; }
    }
}
