//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcECommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishListToProducts
    {
        public int ProductId { get; set; }
        public int WishListId { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Products Products1 { get; set; }
        public virtual WishList WishList { get; set; }
    }
}
